apiVersion: apps/v1
kind: Deployment
metadata:
  name: depoly002
  labels:
    app: depoly002
  namespace: namespace-workflow-1705592954819
spec:
  replicas: 1
  selector:
    matchLabels:
      app: depoly002
  template:
    metadata:
      labels:
        app: depoly002
    spec:
      containers:
        - name: depoly002
          image: acrovi.azurecr.io/image-workflow-1705592954819:latest
          ports:
            - containerPort: 8080