apiVersion: apps/v1
kind: Deployment
metadata:
  name: ovidiunew
  labels:
    app: ovidiunew
  namespace: namespace-workflow-1702980523066
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ovidiunew
  template:
    metadata:
      labels:
        app: ovidiunew
    spec:
      containers:
        - name: ovidiunew
          image: acrworkflow1702980523066.azurecr.io/image-workflow-1702980523066:latest
          ports:
            - containerPort: 8000