apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy001
  labels:
    app: autodeploy001
  namespace: namespace-workflow-1705591713349
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy001
  template:
    metadata:
      labels:
        app: autodeploy001
    spec:
      containers:
        - name: autodeploy001
          image: acrovi.azurecr.io/image-workflow-1705591713349:latest
          ports:
            - containerPort: 8000