apiVersion: apps/v1
kind: Deployment
metadata:
  name: testoviiu
  labels:
    app: testoviiu
  namespace: namespace-workflow-1701064300067
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testoviiu
  template:
    metadata:
      labels:
        app: testoviiu
    spec:
      containers:
        - name: testoviiu
          image: acrworkflow1701064300067.azurecr.io/image-workflow-1701064300067:latest
          ports:
            - containerPort: 8000