apiVersion: apps/v1
kind: Deployment
metadata:
  name: automatic-deployment
  labels:
    app: automatic-deployment
  namespace: automatic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: automatic-deployment
  template:
    metadata:
      labels:
        app: automatic-deployment
    spec:
      containers:
        - name: automatic-deployment
          image: acrworkflow1706607049571.azurecr.io/image-workflow-1706607049571:latest
          ports:
            - containerPort: 8080