apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksmain
  labels:
    app: aksmain
  namespace: automattic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksmain
  template:
    metadata:
      labels:
        app: aksmain
    spec:
      containers:
        - name: aksmain
          image: acrworkflow1708435141622.azurecr.io/image-workflow-1708435141622:latest
          ports:
            - containerPort: 8080