apiVersion: v1
kind: Service
metadata:
  name: ovidiunew
  namespace: namespace-workflow-1702980523066
spec:
  type: LoadBalancer
  selector:
    app: ovidiunew
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000