apiVersion: v1
kind: Service
metadata:
  name: automatic-deployment
  namespace: automatic
spec:
  type: LoadBalancer
  selector:
    app: automatic-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080