apiVersion: v1
kind: Service
metadata:
  name: depoly002
  namespace: namespace-workflow-1705592954819
spec:
  type: LoadBalancer
  selector:
    app: depoly002
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080