apiVersion: v1
kind: Service
metadata:
  name: autodeploy001
  namespace: namespace-workflow-1705591713349
spec:
  type: LoadBalancer
  selector:
    app: autodeploy001
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000