apiVersion: v1
kind: Service
metadata:
  name: test003
  namespace: namespace-workflow-1705923048608
spec:
  type: LoadBalancer
  selector:
    app: test003
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080