apiVersion: v1
kind: Service
metadata:
  name: ovidiu
  namespace: namespace-workflow-1695895317543
spec:
  type: LoadBalancer
  selector:
    app: ovidiu
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080