apiVersion: v1
kind: Service
metadata:
  name: aksmain
  namespace: automattic
spec:
  type: LoadBalancer
  selector:
    app: aksmain
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080