apiVersion: v1
kind: Service
metadata:
  name: testoviiu
  namespace: namespace-workflow-1701064300067
spec:
  type: LoadBalancer
  selector:
    app: testoviiu
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000